# [START app_yaml]
runtime: nodejs10
default_expiration: "10d"
handlers:
  - url: /static
    static_dir: build
    secure: always
    redirect_http_response_code: 301
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301